# Package overview
package_name: classification_model

# Data Files
training_data_file: Social_Network_Ads.csv
test_data_file: test.csv

model_save_file: classification_model_output_v

predict_data_file: predicted_data 


# Variable
# Variable or label we are trying to predict
target: Purchased

features:
  - Age
  - EstimateSalary

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0  